server:
  port: 8090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  r2dbc:
    url: r2dbc:postgresql://localhost/userdb
    username: admin1234
    password: secret1234